<!-- Affichage galerie -->
    <?php if(!isset($_GET['method'])): ?>
    <section class="d-flex flex-column align-items-center">
        <h2 class="text-center my-3">Galerie</h2>
        <a class="btn btn-success" href="?page=image&method=add">Nouvelle image</a>
    </section>
    <section class="container-fluid d-flex flex-wrap gap-2 justify-content-center mt-3 mb-3">
        <?php foreach($data['gallery'] as $i) : ?>
            <article class="card col-sm-12 col-md-5 col-lg-3">
                <a href="?page=details&id=<?= $i['id']?>" style="height: 230px; overflow:hidden;"><img src=<?= $i['src']?> alt="<?= $i['title']?>" title="<?= $i['description'].' par '.$i['author']; ?>" class="card-img-top"></a>
                <div class="card-body">
                    <h5 class="card-title"><?= $i['title']; ?></h5>
                    <a href="?page=image&method=edit&id=<?= $i['id']?>" class="btn btn-secondary"><small>Éditer</small></a>
                    <a href="?page=image&method=delete&id=<?= $i['id']?>" class="btn btn-danger"><small>Supprimer</small></a>
                </div>
                <div class="card-footer">
                    <small class="text-body-secondary"><a href="<?= $i['author_link']?>" class="text-body-secondary" target="_blank"><?= $i['author']?></a><?=' - Le '.date_format(date_create($i['date_added']),"d M Y"); ?></small>
                </div>
            </article>
        <?php endforeach; ?>
    </section>
    <?php endif; ?>
<!-- Fin affichage galerie -->

