<section class="m-auto">
    <h2 class="text-center mt-5">Inscription</h2>
    <form method="POST" class="w-50 card p-4 mx-auto mb-3">
        <div class="form-group mb-2">
            <label for="firstName">Prénom<span class="text-danger">*</span></label>
            <input type="text" class="form-control" id="firstName" name="firstName" placeholder="Prénom" required>
        </div>

        <div class="form-group mb-2">
            <label for="lastName">Nom<span class="text-danger">*</span></label>
            <input type="text" class="form-control" id="lastName" name="lastName" placeholder="Nom" required>
        </div>

        <div class="form-group mb-2">
            <label for="mail">Adresse e-mail<span class="text-danger">*</span></label>
            <input type="email" class="form-control" id="mail" name="mail" aria-describedby="emailHelp" placeholder="Email" required>
            <small id="emailHelp" class="form-text text-muted">We'll never share your email with anyone else.</small>
        </div>

        <div class="form-group mb-2">
            <label for="password">Mot de passe<span class="text-danger">*</span></label>
            <input type="password" class="form-control" id="password" name="password" placeholder="Mot de passe" required>
        </div>

        <button type="submit" name="newUser" class="btn btn-primary mb-2 mt-2">Confirmer mon inscription</button>
        <?php foreach($data['errors'] as $e) : ?>
            <p class="text-danger text-center mb-0"><?= $e ?></p>        
        <?php endforeach; ?>
    </form>
</section>